name: Documentation

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        bundler-cache: true
    - name: Install doxygen and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install doxygen graphviz
    - name: Generate the templates
      run: bundle exec rake templates
    - name: Check ruby coverage
      run: bundle exec rake rdoc:coverage
    - name: Check C coverage
      run: doxygen Doxyfile
    - name: Check Java coverage
      run: javadoc -Xdoclint:all,-missing -d ../doc/java -subpackages *
      working-directory: java
